#title in header
title: "KHRONOS"

#main info
#owner
#owner: "I am Khronos"
email: Khronos@Khronos.moe
info: "æ—…å±…åŒ—ç¾ åˆšä¸‹é£æœº"
#description
desc: "I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the TannhÃ¤user Gate. All those moments will be lost in time, like tears in rain."

#menu
#menu:
#  Works: /Works
#  About: /About

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/khronosmoe
#linkedin: https://linkedin.com/in/adisaktijrs
#twitter: https://twitter.com/adisaktijrs
#instagram: https://instagram.com/adisaktijrs
#stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.jpg
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
